package de.mbs.gallery.client.event;

public enum EMenuItem {
  SHOW_DOWNLOAD_VIEW,
  SHOW_GALLERY,
  SHOW_NEXT_IMAGE,
  SHOW_PREVIOUS_IMAGE,
  SUBMIT_ORDER,
  SHOW_ORDER,
  ZIP_DOWNLOAD,
  SHOW_GALLERY_ADMIN_PANEL,
  SHOW_ADMIN_PANEL,
  SHOW_ORDER_ADMIN_PANEL
}
